sudo: false
language: python
python: "2.7_with_system_site_packages"
install:
  - python setup.py install
script:
  - image3font.hy --version
addons:
    apt:
        packages:
            - fontforge-nox
            - python-fontforge
