sudo: false
language: python
python: "2.7_with_system_site_packages"
install:
  - pip install -r requirements.txt
  - pip install -e .
script:
  - fontforge --version
  - whereis python
  - python2 -c "import fontforge; print(fontforge)"
  - hy image3font/image3font.hy --version
cache: pip
addons:
    apt:
        packages:
            - fontforge-nox
            - python-fontforge
