sudo: false
language: python
python: "2.7_with_system_site_packages"
cache: pip
install:
#  - pip install -r requirements.txt
#  - pip install -e .
  - python setup.py install
script:
  - image3font.hy --version
addons:
    apt:
        packages:
            - fontforge-nox
            - python-fontforge
