sudo: true
language: python
python:
  - "2.7"
install:
  - sudo apt-get install fontforge python2.7-fontforge 
  - pip install -r requirements.txt
  - pip install -e .
script:
  - fontforge --version
  - whereis python
  - python2 -c "import fontforge; print(fontforge)"
  - hy image3font/image3font.hy --version
cache: pip
