sudo: false
language: python
python: "2.7_with_system_site_packages"
cache: pip
install:
  - pip install git+https://github.com/behdad/fontTools.git
  - pip install -r requirements.txt
  - pip install -e .
script:
  - cd image3font
  - hy image3font.hy --version
addons:
    apt:
        packages:
            - fontforge-nox
            - python-fontforge
