sudo: true
language: python
python:
  - "2.7"
env: 
  global:
    - PYTHON_CFLAGS=$(python2-config --cflags)
    - PYTHON_LIBS=$(python2-config --libs)
install:
  - sudo apt-get remove -y python3
  - sudo apt-get install fontforge 
  - pip install -r requirements.txt
  - pip install -e .
script:
  - fontforge --version
  - whereis python
  - python2 -c "import fontforge; print(fontforge)"
  - hy image3font/image3font.hy --version
cache: pip
