language: python
before_install:
  - sudo add-apt-repository --yes ppa:fontforge/fontforge
  - sudo add-apt-repository -y ppa:chris-lea/node.js
  - sudo add-apt-repository -y ppa:hash3g/ots
  - sudo apt-get update -qq
  - sudo apt-get install python-fontforge ttfautohint nodejs swig otsanitizer
install:
  - pip install -r requirements.txt
  - pip install -e .
script:
  - fontforge --version
  - whereis python
  - python2 -c "import fontforge; print(fontforge)"
  - hy image3font/image3font.hy --version
cache: pip
